server:
  port: 8963

spring:
  application:
    name: consumer-user-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 开启hystrix熔断器
feign:
  hystrix:
    enabled: true