spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-client

  profiles:
    active: native

  application:
    name: config-server

server:
  port: 8888